sudo: required
language: python
cache:
  pip: true
  directories:
    - node_modules
python:
  - 3.5
  - 3.6
addons:
  chrome: stable
install:
  - wget https://chromedriver.storage.googleapis.com/2.40/chromedriver_linux64.zip && unzip chromedriver_linux64.zip -d chromedriver && export PATH=$PATH:$PWD/chromedriver
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install 8
  - npm install -g gulp-cli npm && npm install
  - pip install pipenv && pipenv install --dev --system
script:
  - travis_retry gulp coverage:production
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/472a0b23105e5b1ecde4
    on_success: change
    on_failure: always
    on_start: never
