sudo: false
dist: trusty
language: python
cache:
  pip: true
  directories:
    - node_modules
python:
  - 3.4
  - 3.5
  - 3.6
env:
  - MOZ_HEADLESS=1
addons:
  firefox: latest
install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.19.1/geckodriver-v0.19.1-linux64.tar.gz && mkdir geckodriver && tar -zxf geckodriver-v0.19.1-linux64.tar.gz -C geckodriver && export PATH=$PATH:$PWD/geckodriver
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install 8
  - npm install -g gulp-cli npm && npm install
  - pip install pipenv && pipenv install --dev --system
before_script:
  - gulp lint
  - gulp build --production
script:
  - travis_retry gulp coverage
after_success:
  - pipenv run coveralls
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/103776b2181f986558f7
    on_success: change
    on_failure: always
    on_start: never
