version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: daphne timestrap.asgi:application --port 80 --bind 0.0.0.0 -v2
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      - SECRET_KEY=CHANGE-ME
