version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: gunicorn timestrap.wsgi:application --timeout 30 --log-file -
    ports:
      - "80:8000"
    depends_on:
      - db
